name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["client QA"]
assignees:
  - egasparini
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device were you using when you encountered this issue?
      options:
        - MacBook
        - iPhone
        - iPad
        - Windows Laptop
        - Android Phone
  - type: dropdown
    id: browser
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: issue_type
    attributes:
      label: What kind of issue is it?
      multiple: true
      options:
        - Backlog / New idea
        - Bug 
        - Copy
        - Design (e.g. Font, Images, User Flow)
        - Email
        - Question
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      multiple: false
      options:
        - High
        - Medium
        - Low
  - type: dropdown
    id: user_type
    attributes:
      label: User Type
      multiple: false
      options:
        - Logged in Admin
        - Logged in Processor
        - Logged in Practitioner
        - Logged in Participant
        - Not logged in
        - Rater
        - All users
  - type: textarea
    id: description
    attributes:
      label: "Please describe your issue:"
      description: What were you trying to do, what happened and what did you expect to happen? In case of a new idea or a question, what's on your mind?
    validations:
      required: true
  - type: input
    id: URL
    attributes:
      label: Page URL
      description: Please provide the relevant URL
    validations:
        required: false
  - type: input
    id: screenshot
    attributes:
      label: Add a screenshot
      description: "Please upload a screenshot of your issue to this folder https://tinyurl.com/587k8z57 and then provide the file URL in the input field below"
      placeholder: "e.g. https://drive.google.com/drive/..."
    validations:
        required: false
  - type: input
    id: loom-video
    attributes:
      label: Add a video link
      description: "If possible it would be even more helpful if you could include a screen recording of the issue. We strongly recommend using Loom as it gives you a link you can then share below. You can create your own Loom account here: https://www.loom.com/signup"
      placeholder: "e.g. https://www.loom.com/..."
    validations:
        required: false

