name: "Bug Report"
description: "File a bug report"
title: "[Bug]: "
labels: ["client QA"]
assignees:
  - egasparini
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
  - type: textarea
    id: what-happened
    attributes:
      label: Briefly describe your issue
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device were you using when you encountered this issue?
      options:
        - MacBook
        - iPhone
        - iPad
        - Windows Laptop
        - Android Phone
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
      validations:
        required: true
    
  - type: dropdown
    id: issue_type
    attributes:
      label: What kind of issue is it?
      multiple: true
      options:
        - Backlog / New idea
        - Bug 
        - Copy
        - Design (e.g. Font, Images, User Flow)
        - Email
        - Question
      validations:
        required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      multiple: false
      options:
        - High
        - Medium
        - Low
      validations:
        required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
